runtime: python310

entrypoint: gunicorn -b :$PORT app.app:app

env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "app.app"

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

env: standard 