AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Cloud Testing Demo

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    MemorySize: 256

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /api/hello
            Method: get
        EchoApi:
          Type: Api
          Properties:
            Path: /api/echo
            Method: post
        HealthApi:
          Type: Api
          Properties:
            Path: /api/health
            Method: get

Outputs:
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction.Arn
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/" 