name: Azure Web App Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'lamda-cloud-testing'    # set this to your web app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'              # set this to the path to your web app project
  PYTHON_VERSION: '3.9'                      # set this to the Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install System Dependencies'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libssl-dev zlib1g-dev

    - name: 'Install Dependencies'
      shell: bash
      run: |
        pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-cache-dir -r requirements.txt
        popd

    - name: 'Run Tests'
      shell: bash
      run: |
        pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        python -m pytest tests/ -v
        popd

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 