name: Deploy to Google Cloud Platform

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: 'lamda-cloud-tes'
  PYTHON_VERSION: '3.9'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install Dependencies'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Run Tests'
      shell: bash
      run: |
        python -m pytest tests/ -v

    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1

    - name: 'Configure GCP Project'
      run: |
        gcloud config set project ${{ env.GCP_PROJECT_ID }}

    - name: 'Enable required APIs'
      run: |
        gcloud services enable cloudbuild.googleapis.com appengine.googleapis.com

    - name: 'Deploy to App Engine'
      run: |
        gcloud app deploy --quiet 